trigger:
  - main  # Runs when you push to main branch

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: "Build Stage"
    jobs:
      - job: BuildJob
        displayName: "Build Job"
        steps:
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)'
              Contents: '**'  # Includes all files (HTML, CSS, JS)
              TargetFolder: '$(Build.ArtifactStagingDirectory)'

          - task: PublishBuildArtifacts@1
            displayName: "Publish Artifact"
            inputs:
              pathToPublish: '$(Build.ArtifactStagingDirectory)'
              artifactName: 'drop'  # This makes sure the artifact is available for deployment

  - stage: Deploy
    displayName: "Deploy Stage"
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: DeployJob
        displayName: "Deploy Job"
        steps:
          - task: DownloadBuildArtifacts@0
            displayName: "Download Build Artifacts"
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'  # Name should match the one in PublishBuildArtifacts
              downloadPath: '$(Pipeline.Workspace)'  # Downloads to default workspace

          - task: AzureWebApp@1
            displayName: "Deploy to Azure Web App"
            inputs:
              azureSubscription: 'azureserviceconnectioncicd'
              appType: 'webAppLinux'
              appName: 'cicdsample'
              package: '$(Pipeline.Workspace)/drop'
              runtimeStack: 'STATICSITE|1.0'
