trigger:
  - main  # Runs when you push to the main branch

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: "Build Stage"
    jobs:
      - job: BuildJob
        displayName: "Build Job"
        steps:
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)'
              Contents: '**'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'

          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: '$(Build.ArtifactStagingDirectory)'
              artifactName: 'drop'

  - stage: Deploy
    displayName: "Deploy Stage"
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: DeployJob
        displayName: "Deploy Job"
        steps:
          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'azureserviceconnectioncicd'
              appName: 'cicdsample'
              package: '$(Pipeline.Workspace)/drop'
